apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-dotnet-basic-ksvcvmua
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/chetna14manku_org/backend-tests-dotnet-basic-ksvcvmua:3dbb664a7a992585e6ee2de236a6ed91006fc38f
        name: container-image  
